
twitter :
  consumer_key : '' ## => http://dev.twitter.com
  consumer_secret : '' ## => http://dev.twitter.com
  access_token : ''
  access_secret : ''

mongo :
  host : localhost
  port : 27017
  database : fvrt
